---
- name: install packages necessary tmux
  yum: name={{ item }} state=present
  with_items:
    - wget
    - gcc 
    - make
    - ncurses
    - ncurses-devel 
    - libevent-devel
  sudo: yes
  tags:
    - package
    - tmux

- name: download libevent
  shell: curl -L https://github.com/downloads/libevent/libevent/libevent-{{libevent_version}}.tar.gz -o /usr/local/src/libevent-{{libevent_version}}.tar.gz
  sudo: yes
  tags:
    - tmux

- name: unzip libevent
  shell: tar xfC /usr/local/src/libevent-{{libevent_version}}.tar.gz /usr/local/src
  sudo: yes
  tags:
    - tmux

- name: make install libevent
  shell: cd /usr/local/src/libevent-{{libevent_version}} && ./configure --prefix=/usr/local && make && make install
  sudo: yes
  tags:
    - tmux

- name: download tmux
  get_url: url=http://sourceforge.net/projects/tmux/files/tmux/tmux-1.9/tmux-1.9.tar.gz/download dest=/usr/local/src/tmux-{{ tmux_version }}.tar.gz
  sudo: yes
  tags:
    - tmux

- name: unzip tmux
  shell: tar xfC /usr/local/src/tmux-{{tmux_version}}.tar.gz /usr/local/src
  sudo: yes
  tags:
    - tmux

- name: make install tmux
  shell: cd /usr/local/src/tmux-{{tmux_version}} && LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local && make && sudo make install
  sudo: yes
  tags:
    - tmux

