---
- name: upgrade all packages
  yum: name=* state=latest
  sudo: yes
  # tags:
    # - package

- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - vim
    - libselinux-python
  sudo: yes
  tags:
    - package
