---
- name: install perl
  yum: name={{ item }} state=present
  with_items:
    - perl
  sudo: yes
  tags:
    - package
    - nodejs

- name: download nodebrew
  get_url: url="http://git.io/nodebrew" dest=/usr/local/src/nodebrew
  sudo: yes
  tags:
    - nodejs

- name: install nodebrew
  shell: perl /usr/local/src/nodebrew setup
  tags:
    - nodejs

- name: add nodebrew path to shell
  shell: echo export PATH={{ home }}/.nodebrew/current/bin:$PATH >> {{ home }}/.{{ shell_name }}
  tags:
    - nodejs

- name: install nodebrew {{ nodejs_version }}
  shell: nodebrew install-binary v{{ nodejs_version }}
  ignore_errors: true
  tags:
    - nodejs

- name: use {{ nodejs_version }}
  shell: nodebrew use v{{ nodejs_version }}
  tags:
    - nodejs

