---

- name: install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest={{ home }}/.rbenv executable={{ git_path }}
  tags:
    - ruby

- name: install ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{ home }}/.rbenv/plugins/ruby-build executable={{ git_path }}
  tags:
    - ruby

- name: add rbenv path to bashrc
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH" eval "$(rbenv init -)"' >> {{ home }}/.bashrc
  tags:
    - ruby

- name: install ruby version {{ ruby_version }}
  shell: rbenv install -v {{ ruby_version }} executable={{ home }}/.rbenv/bin/rbenv
  tags:
    - ruby
