---
- hosts: target
  sudo: yes

  tasks:
  - name: install 'Development tools' package group
    yum: name="@Development tools" state=present
    tags:
      - package

  - name: install package
    yum: name={{item}} state=latest
    with_items:
      - libselinux-python
      - gitflow
      - ctags
      - dstat
      - telnet
      - docker
      - the_silver_searcher
    tags:
      - package
