---
- hosts: target
  vars:
    shell: ".zshrc"
    rbenv:
      bin: "~/.rbenv/bin/rbenv"
    ruby:
      version: "2.3.0"
    gem:
      version: "2.5.1"

  tasks:
  - name: install dependencies for rbenv and ruby-build
    sudo: yes
    yum: name={{item}} state=latest
    with_items:
      - git
      - tar
      - gcc
      - make
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - zlib-devel
      - gdbm-devel
      - ncurses-devel

  - name: install rbenv
    git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
    tags:
      - ruby

  - name: install ruby-build
    git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
    tags:
      - ruby

  - name: add ~.rbenv/bin to PATH
    lineinfile: >
      create=yes
      state=present
      dest=~/{{shell}}
      line="export PATH=$HOME/.rbenv/bin:$PATH"
    tags:
      - ruby

  - name: eval rbenv init in shell
    lineinfile: >
      create=yes
      state=present
      dest=~/{{shell}}
      line='eval "$(rbenv init -)"'
    tags:
      - ruby

  - name: check if {{ruby.version}} is installed
    shell: "{{rbenv.bin}} versions | grep {{ruby.version}}"
    register: rbenv_check_install
    changed_when: False
    ignore_errors: True
    tags:
      - ruby

  - name: install ruby version {{ruby.version}}
    shell: "{{rbenv.bin}} install -v {{ruby.version}}"
    when: rbenv_check_install|failed
    tags:
      - ruby

  - name: check if {{ ruby.version }} is the default ruby version
    shell: "{{rbenv.bin}} version | grep {{ ruby.version }}"
    register: rbenv_check_default
    changed_when: False
    ignore_errors: True
    tags:
      - ruby

  - name: version specified to be used
    shell: "{{rbenv.bin}} global {{ ruby.version }}"
    when: rbenv_check_default|failed
    tags:
      - ruby

  - name: rbenv rehash
    shell: "{{rbnev.bin}} rehash"
    when: rbenv_check_default|failed
    tags:
      - ruby

  - name: gem install bundler on rbenv
    gem:
      name=bundler
      state=present
      executable=~/.rbenv/shims/gem
      user_install=False
    when: rbenv_check_default|failed
    tags:
      - ruby
