---
- hosts: target
  sudo: yes
  vars:
    nginx:
      repository: "http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm"

  tasks:
  - name: nginx repository install
    yum: name={{nginx.repository}} state=present
    tags:
      - nginx

  - name: nginx install
    yum: name=nginx state=present
    tags:
      - nginx

  - name: nginx boot and restart
    service: name=nginx enabled=yes state=restarted
    tags:
      - nginx
