---
- hosts: target
  sudo: yes

  tasks:
  - name: install pip
    yum: name={{item}} state=latest
    with_items:
      - python-pip
    tags:
      - aws

  - name: pip upgrade and install aws
    shell: pip install --upgrade awscli --user
    tags:
      - aws
