---
- hosts: vagrant
  sudo: yes
  vars_files:
    - users.yml

  tasks:
  - name: create new user
    user: >-
      name={{item.name}}
      password={{item.pass}}
      createhome=yes
      state=present
    with_items: "{{ users }}"
    tags:
      - useradd

  - name: install 'Development tools' package group
    yum: name="@Development tools" state=present
    tags:
      - useradd

  - name: install 'libselinux-python' package
    yum: name=libselinux-python state=latest
    tags:
      - useradd

  - name: add sudo user
    lineinfile: >-
      dest=/etc/sudoers
      backup=yes
      create=yes
      line='{{item.name}} ALL=(ALL) NOPASSWD: ALL'
    with_items: "{{ users }}"
    tags:
      - useradd

  - name: create ssh directory
    file: path=/home/{{item.name}}/.ssh state=directory owner={{item.name}} group=users mode=700
    with_items: "{{ users }}"
    tags:
      - useradd

  - name: setup authorized_keys
    authorized_key: >-
      user={{item.name}}
      key="{{item.key}}"
    with_items: "{{ users }}"
    tags:
      - useradd
